 name: Github Actions Demo First
 on: [push]
 jobs:
   Explore-Github-Actions:
     runs-on: ubuntu-latest
     steps:
       - run: the name of your branch is ${{ github.ref }} and your repo is ${{ github.repository }}"
       - run: echo "The job was automatically triggered by a ${{ github.event_name }} event!"
       - run: echo " This job is now running on a ${{ runner.os }} server hosted by Github"
       - name: Check out repo code
         uses: actions/checkout@v3
       - run: echo "The ${{ github.repository }} has been cloned to the runner
       - name: List files in the repo
         run: |
          ls ${{ github.workspace }}
       - run: echo "This job's status is ${{ job.status }}"

